// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderSystemV1.Infra.SqlDbContext;

namespace OrderSystemV1.Infra.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20220529185038_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.HasSequence<int>("RefenceProduct")
                .StartsAt(1000L);

            modelBuilder.HasSequence<int>("ReferenceClient")
                .StartsAt(1000L);

            modelBuilder.Entity("OrderSystemV1.Domain.Entity.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CLIENT_BIRTHDATE");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CLIENT_EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLIENT_NAME");

                    b.Property<int>("ReferenceClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CLIENT_REF")
                        .HasDefaultValueSql("NEXT VALUE FOR ReferenceClient");

                    b.HasKey("Id");

                    b.ToTable("TB_CLIENT");
                });

            modelBuilder.Entity("OrderSystemV1.Domain.Entity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PRODUCT_NAME");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal")
                        .HasColumnName("PRODUCT_PRICE");

                    b.Property<int>("RefenceProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_REFERENCE")
                        .HasDefaultValueSql("NEXT VALUE FOR RefenceProduct");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUCT");
                });
#pragma warning restore 612, 618
        }
    }
}
